const textoErro = "<img src='assets/img/browser_sad.png' style='width:200px; margin-bottom:20px'> <br/>Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"

const perguntas = [
    {
        enunciado: "Vamos criar uma parte do estilo CSS da nossa página de FlashCards e customizar a página web abaixo ?",
        imagem: "assets/img/pagina_HTML.png",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Sim, vamos! Eu já tenho o código HTML em meu projeto.",
                afirmacao: "X",
                correta: true,
                img: "",
                imgThumb: "",
                correta: true,
                recompensa: false,
                linguagem: "",
                textoRecompensa: ""
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Sim, vamos! Porém eu NÃO tenho o código HTML em meu projeto.",
                afirmacao: "Tudo bem, copie o código abaixo e insira dentro do seu arquivo index.html",
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: true,
                linguagem: "language-html",
                textoRecompensa: codigoHTML
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "",
        textoErrado: ""
    },
    {
        enunciado: "Nossa página terá uma imagem de plano de fundo.<br>Qual imagem abaixo você gostaria de ter como fundo?",
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-blue.webp)",
                texto: "<span>Tons em azul</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-blue-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-blue.webp",
                imgThumb: "assets/img/bg-desktop-blue-thumb.jpg",
                recompensa: true,
                linguagem: false,
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-blue.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-red.webp)",
                texto: "<span>Tons em vermelho</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-red-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-red.webp",
                imgThumb: "assets/img/bg-desktop-red-thumb.jpg",
                recompensa: true,
                linguagem: "",
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-red.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-yellow.webp)",
                texto: "<span>Tons em amarelo</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-yellow-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-yellow.webp",
                imgThumb: "assets/img/bg-desktop-yellow-thumb.jpg",
                recompensa: true,
                linguagem: "",
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-yellow.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: `Precisamos colocar a imagem que escolheu como fundo no elemento body. 
        Para fazer isso, iremos inserir códigos no arquivo style.css, seguindo a seguinte sintaxe: <br>
        <img src='assets/img/pergunta-background.png'><br/>
        <!-- <ol>
        <li> selecionar o body</li>
        <li> definir um bloco de estilização com abre { e fecha } chaves</li>
        <li> inserir propriedade de estilo</li>
        <li> atribuir um valor com dois pontos : </li>
        <li> inserir o valor que é um arquivo por isso utilizamos a url</li>
        </ol> -->
        Porém qual será essa propriedade que inseri imagem a um plano de fundo da nossa página ?
        `,
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "color",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background-color",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: textoErro
    },
    {
        enunciado: "A fonte ou estilo das letras de nosso página é algo marcante. Por isso busquei do GoogleFonts algumas opções, escolha qual você gostou mais?",
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Bai Jamjuree",
                texto: `<span class='bai-jamjuree'>Bai Jamjuree<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Josefin Sans",
                texto: `<span class='josefin-sans'>Josefin Sans<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Tomorrow",
                texto: `<span class='tomorrow'>Tomorrow<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Grandstander",
                texto: `<span class='grandstander'>Grandstander<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Handjet",
                texto: `<span class='handjet'>Handjet<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Niramit",
                texto: `<span class='niramit'>Niramit<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Gluten",
                texto: `<span class='gluten'>Gluten<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Vamos colorir nossa página web. Escolha uma das cores abaixo para ser a cor da frente do seu cartão?",
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#144480",
                texto: "<div id='azul' class='espacamento-cores'>Azul</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: "<div id='azul-escuro' class='espacamento-cores'>Azul escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#AF3438",
                texto: "<div id='vermelho' class='espacamento-cores'>Vermelho</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Escolha agora uma das cores abaixo para ser a cor de tráz do seu cartão?",
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#144480",
                texto: "<div id='azul' class='espacamento-cores'>Azul</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: "<div id='azul-escuro' class='espacamento-cores'>Azul escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#AF3438",
                texto: "<div id='vermelho' class='espacamento-cores'>Vermelho</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Agora escolha a cor do texto?",
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#144480",
                texto: `<div id='texto-azul' class='espacamento-cores'>Azul</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: `<div id='texto-azul-escuro' class='espacamento-cores'>Azul Escuro</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#AF3438",
                texto: `<div id='texto-vermelho' class='espacamento-cores'>Vermelho</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='texto-vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='texto-amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='texto-amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#ffffff",
                texto: "<div id='texto-branco' class='espacamento-cores'>Branco</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#000000",
                texto: "<div id='texto-preto' class='espacamento-cores'>Preto</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: true,
        blocoCSS: "body",
        textoErrado: "",
        imgRecompensa: "",
    },
    {
        enunciado: `Vamos estilizar o elemento com classe "cartao__conteudo". Primeiro inserimos uma cor de fundo, utilizando da variável que criamos chamada --card-front-color. Quais das opções abaixo aplica cor de fundo utilizando nossa variável ?`,
        imagem: "assets/img/background_cartao.png",
        posicaoImg: "top", 
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background: var(--card-front-color);",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background-color: --card-front-color;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "background-color",
                valorPropriedadeCSS: "var(--card-front-color)",
                texto: "background-color: var(--card-front-color);",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: ".cartao__conteudo",
        textoErrado: textoErro
    },
    {
        enunciado: `Qual propriedade CSS e valor abaixo você considera que deixará o texto do cartão centralizado ?`,
        imagem: "assets/img/texto_centralizado_cartao.png",
        posicaoImg: "top", 
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "align-text: centro;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "text-align",
                valorPropriedadeCSS: "center",
                texto: "text-align: center;",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "text-align: justify;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo",
        textoErrado: textoErro
    },
    /*{
        enunciado: `Ainda no elemento com classe "cartao__conteudo" vamos inserir a seguinte declaração de estilo "height: 100%;". Qual seria o motivo da utilização de mais esta linha de estilo neste elemento?`,
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "O elemento com classe cartao_conteudo precisa possuir uma largura de 100% da página!",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "height",
                valorPropriedadeCSS: "100%",
                texto: "O elemento com classe cartao_conteudo engloba outros elementos e por isso precisamos definir uma altura que mostre 100% do seu conteúdo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "É somente uma propriedade que define boa aparência visual, podendo ser desnecessária.",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo",
        textoErrado: textoErro
    },*/
    {
        enunciado: `Você está organizando os cartões da sua página, como mostrado na imagem. Antes, eles apareciam empilhados, um embaixo do outro. Agora, eles estão organizados lado a lado. Qual valor da propriedade display permite esse comportamento?`,
        imagem: "assets/img/display_flex_cartao.png",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "display",
                valorPropriedadeCSS: "block",
                texto: "block",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "#container",
                propriedadeCSS : "display",
                valorPropriedadeCSS: "inline",
                texto: "inline",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "#container",
                propriedadeCSS : "display",
                valorPropriedadeCSS: "flex",
                texto: "flex",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "#container",
        textoErrado: textoErro
    },
    {
        enunciado: `A propriedade flex-basis, quando aplicada a um elemento filho de um contêiner com display: flex, define sua largura inicial. Queremos que uma linha do layout tenha três cartões, ou seja, cada cartão deve ocupar 1/3 do contêiner. No entanto, cada cartão possui uma margem de 1rem à direita e à esquerda. Qual das opções abaixo representa o cálculo correto para definir a largura desses cartões?`,
        imagem: "assets/img/flex-basis.png",
        posicaoImg: "top", 
        alternativas: [
            {
                blocoCSS: ".cartao",
                propriedadeCSS : "flex-basis",
                valorPropriedadeCSS: "math(1/3 - 6rem)",
                texto: "math(1/3 - 6rem)",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao",
                propriedadeCSS : "flex-basis",
                valorPropriedadeCSS: "calc(33% - 3rem)",
                texto: "calc(33% - 3rem)",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao",
                propriedadeCSS : "flex-basis",
                valorPropriedadeCSS: "calc(33% - 6rem)",
                texto: "calc(33% - 6rem)",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao",
        textoErrado: textoErro
    },
    {
        enunciado: `Queremos que os parágrafos dentro do cartão tenham um espaçamento interno, para que os textos fiquem afastados, representando uma divisão clara dentro do conteúdo. Qual propriedade utilizamos para aplicar esse espaçamento interno?`,
        imagem: "assets/img/espacamento_interno.png",
        posicaoImg: "top", 
        alternativas: [
            {
                blocoCSS: ".cartao__conteudo p",
                propriedadeCSS : "padding",
                valorPropriedadeCSS: "4rem",
                texto: "padding",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo p",
                propriedadeCSS : "border",
                valorPropriedadeCSS: "4rem",
                texto: "border",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo p",
                propriedadeCSS : "margin",
                valorPropriedadeCSS: "4rem",
                texto: "margin",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo p",
        textoErrado: textoErro
    },
    {
        enunciado: `Precisamos posicionar o subtítulo "programação" no canto superior esquerdo de cada cartão, sem que ele afete a disposição ou o fluxo dos outros elementos dentro do cartão. Qual propriedade e valor abaixo resultaria nesse comportamento?`,
        imagem: "assets/img/position_absolute.png",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: ".cartao__conteudo h3",
                propriedadeCSS : "position",
                valorPropriedadeCSS: "relative",
                texto: "position: relative;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo h3",
                propriedadeCSS : "position",
                valorPropriedadeCSS: "fixed",
                texto: "position: fixed;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo h3",
                propriedadeCSS : "position",
                valorPropriedadeCSS: "absolute",
                texto: "position: absolute;",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo h3",
        textoErrado: textoErro
    },
    {
        enunciado: `Para personalizar a aparência de uma página, é comum alterarmos a cor do texto. Qual é a propriedade CSS responsável por definir a cor do conteúdo textual de um elemento?`,
        imagem: "assets/img/cor_do_texto.png",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: ".cartao__conteudo__pergunta p",
                propriedadeCSS : "background-color",
                valorPropriedadeCSS: "var(--text-color)",
                texto: "background-color",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__pergunta p",
                propriedadeCSS : "color",
                valorPropriedadeCSS: "var(--text-color)",
                texto: "color",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__pergunta p",
                propriedadeCSS : "font-style",
                valorPropriedadeCSS: "var(--text-color)",
                texto: "font-style",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo__pergunta p",
        textoErrado: textoErro
    },
    {
        enunciado: `Para destacar títulos ou dar ênfase a certos textos, podemos controlar a espessura da fonte. Qual propriedade CSS é utilizada para ajustar o peso (espessura) de um texto, como torná-lo mais "negrito" ou mais "leve"?`,
        imagem: "assets/img/font-weight.png",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: ".cartao__conteudo__resposta p",
                propriedadeCSS : "font-style",
                valorPropriedadeCSS: "700",
                texto: "font-style",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__resposta p",
                propriedadeCSS : "text-transform",
                valorPropriedadeCSS: "700",
                texto: "text-transform",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__resposta p",
                propriedadeCSS : "font-weight",
                valorPropriedadeCSS: "700",
                texto: "font-weight",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo__resposta p",
        textoErrado: textoErro
    },
    {
        enunciado: `No nosso HTML, temos o elemento &lt;footer&gt;Projeto desenvolvido nos Formadores em Ação&lt;/footer&gt;, que é responsável por representar o conteúdo do rodapé. Sabemos que ele é um elemento único na página. Como você selecionaria esse elemento no CSS?`,
        imagem: "",
        posicaoImg: "", 
        alternativas: [
            {
                blocoCSS: "footer",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Como ele é único, posso selecioná-lo diretamente pelo nome do elemento footer.",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Devo obrigatoriamente criar uma classe e utilizá-la como seletor.",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Devo obrigatoriamente criar um ID e utilizá-lo como seletor.",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "footer",
        textoErrado: textoErro
    },
    {
        enunciado: `O texto do parágrafo contido em nosso rodapé está grande e deve ser mais discreto e menor. Qual das propriedades abaixo permitirá diminuir esse texto?`,
        imagem: "assets/img/font-size.png",
        posicaoImg: "top", 
        alternativas: [
            {
                blocoCSS: "footer p",
                propriedadeCSS : "font-size",
                valorPropriedadeCSS: "0.6rem",
                texto: "font-size",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer p",
                propriedadeCSS : "font-style",
                valorPropriedadeCSS: "0.6rem",
                texto: "font-style",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer p",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "0.6rem",
                texto: "font-family",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "footer p",
        textoErrado: textoErro
    },
];