const perguntas = [
    {
        enunciado: "Vamos customizar a página web abaixo ?",
        imagem: "assets/img/pagina_HTML.png",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Sim, vamos! Eu já tenho o código HTML em meu projeto.",
                afirmacao: "X",
                correta: true,
                img: "",
                imgThumb: "",
                correta: true,
                recompensa: false,
                linguagem: "",
                textoRecompensa: ""
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Sim, vamos! Porém eu NÃO tenho o código HTML em meu projeto.",
                afirmacao: "Tudo bem, copie o código abaixo e insira dentro do seu arquivo index.html",
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: true,
                linguagem: "language-html",
                textoRecompensa: codigoHTML
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "",
        textoErrado: ""
    },
    {
        enunciado: "Nossa página terá uma imagem de plano de fundo.<br>Qual imagem abaixo você gostaria de ter como fundo?",
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-blue.webp)",
                texto: "<span>Tons em azul</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-blue-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-blue.webp",
                imgThumb: "assets/img/bg-desktop-blue-thumb.jpg",
                recompensa: true,
                linguagem: false,
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-blue.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-red.webp)",
                texto: "<span>Tons em vermelho</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-red-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-red.webp",
                imgThumb: "assets/img/bg-desktop-red-thumb.jpg",
                recompensa: true,
                linguagem: "",
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-red.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "background",
                valorPropriedadeCSS: "url(img/bg-desktop-yellow.webp)",
                texto: "<span>Tons em amarelo</span>",
                afirmacao: `Boa escolha!<br /> <img src='assets/img/bg-desktop-yellow-thumb.jpg'>`,
                correta: true,
                img: "assets/img/bg-desktop-yellow.webp",
                imgThumb: "assets/img/bg-desktop-yellow-thumb.jpg",
                recompensa: true,
                linguagem: "",
                textoRecompensa: `<p>ATENÇÃO: A imagem que escolheu precisa ser salva no seu projeto. Baixe o arquivo clicando neste <b> <a href='assets/img/bg-desktop-yellow.webp' download>link</a> </b> e depois coloque-o na pasta <b>assets/img</b>.</p>`
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: `Precisamos colocar a imagem que escolheu como fundo no elemento body. 
        Para fazer isso, iremos inserir códigos no arquivo style.css, seguindo a seguinte sintaxe: <br>
        <img src='assets/img/pergunta-background.png'><br/>
        <!-- <ol>
        <li> selecionar o body</li>
        <li> definir um bloco de estilização com abre { e fecha } chaves</li>
        <li> inserir propriedade de estilo</li>
        <li> atribuir um valor com dois pontos : </li>
        <li> inserir o valor que é um arquivo por isso utilizamos a url</li>
        </ol> -->
        Porém qual é essa propriedade que inseri imagem a um plano de fundo da nossa página ?
        `,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "color",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background-color",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: "A fonte ou estilo das letras de nosso página é algo marcante. Por isso busquei do GoogleFonts algumas opções, escolha qual você gostou mais?",
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Bai Jamjuree",
                texto: `<span class='bai-jamjuree'>Bai Jamjuree<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Josefin Sans",
                texto: `<span class='josefin-sans'>Josefin Sans<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Tomorrow",
                texto: `<span class='tomorrow'>Tomorrow<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Grandstander",
                texto: `<span class='grandstander'>Grandstander<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Handjet",
                texto: `<span class='handjet'>Handjet<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Niramit",
                texto: `<span class='niramit'>Niramit<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "font-family",
                valorPropriedadeCSS: "Gluten",
                texto: `<span class='gluten'>Gluten<span>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Vamos colorir nossa página web. Escolha uma das cores abaixo para ser a cor da frente do seu cartão?",
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#144480",
                texto: "<div id='azul' class='espacamento-cores'>Azul</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: "<div id='azul-escuro' class='espacamento-cores'>Azul escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#AF3438",
                texto: "<div id='vermelho' class='espacamento-cores'>Vermelho</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-front-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Escolha agora uma das cores abaixo para ser a cor de tráz do seu cartão?",
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#144480",
                texto: "<div id='azul' class='espacamento-cores'>Azul</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: "<div id='azul-escuro' class='espacamento-cores'>Azul escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#AF3438",
                texto: "<div id='vermelho' class='espacamento-cores'>Vermelho</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--card-back-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: false,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: "Agora escolha a cor do texto?",
        imagem: "",
        alternativas: [
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#144480",
                texto: `<div id='texto-azul' class='espacamento-cores'>Azul</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#51BBA9",
                texto: `<div id='texto-azul-escuro' class='espacamento-cores'>Azul Escuro</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: false,
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#AF3438",
                texto: `<div id='texto-vermelho' class='espacamento-cores'>Vermelho</div>`,
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#772D2D",
                texto: "<div id='texto-vermelho-escuro' class='espacamento-cores'>Vermelho escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#BC9E3E",
                texto: "<div id='texto-amarelo' class='espacamento-cores'>Amarelo</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#786739",
                texto: "<div id='texto-amarelo-escuro' class='espacamento-cores'>Amarelo escuro</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#ffffff",
                texto: "<div id='texto-branco' class='espacamento-cores'>Branco</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "body",
                propriedadeCSS : "--text-color",
                valorPropriedadeCSS: "#000000",
                texto: "<div id='texto-preto' class='espacamento-cores'>Preto</div>",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            }
        ],
        mostraBlocoCSS: true,
        blocoCSS: "body",
        textoErrado: ""
    },
    {
        enunciado: `Vamos estilizar o elemento com classe "cartao__conteudo". Primeiro vamos inserir uma cor de fundo, utilizando da variável que criamos chamada --card-front-color. Quais das opções abaixo aplica cor de fundo utilizando nossa variável ?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background: var(--card-front-color);",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "background-color: --card-front-color;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "background-color",
                valorPropriedadeCSS: "var(--card-front-color)",
                texto: "background-color: var(--card-front-color);",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: ".cartao__conteudo",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Qual propriedade CSS e valor abaixo você considera que deixará o texto do cartão centralizado ?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "align-text: centro;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "text-align",
                valorPropriedadeCSS: "center",
                texto: "text-align: center;",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "text-align: justify;",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: false,
        blocoCSS: ".cartao__conteudo",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Ainda no elemento com classe "cartao__conteudo" vamos inserir a seguinte declaração de estilo "height: 100%;". Qual seria o motivo da utilização de mais esta linha de estilo neste elemento?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "O elemento com classe cartao_conteudo precisa possuir uma largura de 100% da página!",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo",
                propriedadeCSS : "height",
                valorPropriedadeCSS: "100%",
                texto: "O elemento com classe cartao_conteudo engloba outros elementos e por isso precisamos definir uma altura que mostre 100% do seu conteúdo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "É somente uma propriedade que define boa aparência visual, podendo ser desnecessária.",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do container (display flex)?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "#container",
                propriedadeCSS : "display",
                valorPropriedadeCSS: "flex",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "#container",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do .cartao?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao",
                propriedadeCSS : "margin",
                valorPropriedadeCSS: "1rem 1rem",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do .cartao__conteudo h3?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo h3",
                propriedadeCSS : "color",
                valorPropriedadeCSS: "var(--text-color)",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo h3",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do .cartao__conteudo p?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo p",
                propriedadeCSS : "margin-top",
                valorPropriedadeCSS: "1rem",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo p",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do .cartao__conteudo__pergunta p?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__pergunta p",
                propriedadeCSS : "font-weight",
                valorPropriedadeCSS: "500",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo__pergunta p",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do .cartao__conteudo__resposta p?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: ".cartao__conteudo__resposta p",
                propriedadeCSS : "font-weight",
                valorPropriedadeCSS: "700",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: ".cartao__conteudo__resposta p",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do footer?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer",
                propriedadeCSS : "position",
                valorPropriedadeCSS: "fixed",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "footer",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
    {
        enunciado: `Aqui vai uma pergunta do footer p?`,
        imagem: "",
        alternativas: [
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "footer p",
                propriedadeCSS : "margin-top",
                valorPropriedadeCSS: "0.5rem",
                texto: "Certo",
                afirmacao: ``,
                correta: true,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
            {
                blocoCSS: "",
                propriedadeCSS : "",
                valorPropriedadeCSS: "",
                texto: "Errado",
                afirmacao: ``,
                correta: false,
                img: "",
                imgThumb: "",
                recompensa: false,
                linguagem: "",
                textoRecompensa: ``
            },
        ],
        mostraBlocoCSS: true,
        blocoCSS: "footer p",
        textoErrado: "Você escolheu a opção errada, mas tudo bem, volte e tente novamente!"
    },
];